// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba.Repositorio;

namespace Prueba.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190809200728_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Prueba.Dominio.Protocolos.Protocolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Protocolo");
                });

            modelBuilder.Entity("Prueba.Dominio.Protocolos.Protocolo", b =>
                {
                    b.OwnsMany("Prueba.Dominio.Protocolos.CodigoEvento", "CodigosEvento", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Numero");

                            b1.Property<int>("ProtocoloId");

                            b1.Property<int>("TipoEventoId");

                            b1.HasKey("Id");

                            b1.HasIndex("ProtocoloId");

                            b1.ToTable("CodigosEvento");

                            b1.HasOne("Prueba.Dominio.Protocolos.Protocolo")
                                .WithMany("CodigosEvento")
                                .HasForeignKey("ProtocoloId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
